baseURL = "https://shiyue-li.github.io/"
languageCode = "en-us"
publishDir = "/Users/admin/Documents/GitHub/shiyue-li.github.io/"
title = "Shiyue Li"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-XXXXXXXX-Y"

[params]
    theme_color = "#574CDD"
    description = "Shiyue Li"
    description_photo = "portfolio.jpg" # need update
    favicon = "favicon.png"  # need update
    logo = "logo.png"  # need update
    email = "shiyue.li@yale.edu"
    # facebook = "lex.collado"  # need update
    # twitter = "lexiscollado"  # need update
    # dribbble = "alexiscollado"  # need update
    # linkedin = "https://www.linkedin.com/in/alexander-hans-collado-jr-9444146a"
    github = "https://github.com/shiyue-li"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar.jpg"
    subtitle = "Shiyue Li."
    hero_right = ["**Curiouser and curiouser!**",
    "I'm a first year PhD student, and a Lang Fellow at the [Department of Mathematics at Yale](https://math.yale.edu).",
    "I converged to my current stage of life via wonderful four years at [Harvey Mudd College](https://www.hmc.edu) studying math, CS and music.",
    "At Harvey Mudd, I worked with [Dagan Karp](https://www.math.hmc.edu/~dk/) on thesis [Tropical Derivation of Cohomology Ring of Heavy/light Hassett Spaces](http://scholarship.claremont.edu/cgi/viewcontent.cgi?article=1101&context=hmc_theses) -- a fun project proposed by [Dhruv Ranganathan](http://www.dhruvrnathan.net/)",
    "Before becoming a math major in senior year, I was an absent-minded programmer and was a software engineer intern at Google Research, advised by [Caroline Pantofaru](http://www.pantofaru.com/research/) and [Malcolm Slaney](http://www.slaney.org/malcolm/pubs.html).",
    "In Summer 2018, I'm a mentor at [Canada/USA Mathcamp 2018](https://www.mathcamp.org).",
    "In Fall 2018, I'm the organizer of the [Directed Reading Program](https://math.yale.edu/undergrad-programs/directed-reading-program) at Yale.",
    ]

    # "I'm a first year PhD student, and a Lang Fellow at the Mathematics department of Yale University.
    # I converged to my current stage of life via Harvey Mudd College.
    # Born and raised in Jiangsu, China, I started my adventure in the U.S. as a member
    # of the Summer Science Program NM 2012."]
    resume = "shiyueli_cv.pdf"  # need update

[params.math]
    enable = true
    title = "Mathematics"

[params.travel]
    enable = true
    title = "Travels"

[params.case_studies]
    enable = true
    title = "Teaching"
    subtitle = "Notes and course pages of classes I taught."

[params.footer]
    enable = true
