baseURL = "https://shiyue-li.github.io/"
languageCode = "en-us"
publishDir = "/Users/octoberbear/Documents/GitHub/shiyue-li.github.io"
title = "Shiyue Li"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-XXXXXXXX-Y"
hasCJKLanguage = true

[params]
    theme_color = "#426BBA"
    description = "李诗乐"
    description_photo = "portfolio.png" # need update
    favicon = "favicon.png"  # need update
    logo = "logo.png"  # need update


[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar.jpg"
    subtitle = "Shiyue Li 李詩樂"
    hero_right = [
    "I am a Donald J. Lewis assistant professor at the [University of Michigan](https://lsa.umich.edu/math), mentored by [David Speyer](https://websites.umich.edu/~speyer/).",
    "From 2023 to 2025, I was a member at the [Institute for Advanced Study](https://www.ias.edu), mentored by [June Huh](https://web.math.princeton.edu/~huh/).", 
    "In 2023, I got a PhD in mathematics at [Brown University](https://www.brown.edu/academics/math/), where I was fortunate to be advised by [Melody Chan](https://www.math.brown.edu/~mtchan/). ", 
    "Prior, I spent wonderful four years at [Harvey Mudd College](https://www.hmc.edu); my undergrad thesis work was guided by [Dagan Karp](https://www.math.hmc.edu/~dk/).",
    "Here are my [Curriculum Vitae](http://www.shiyue.li/shiyueli-website-2025.pdf), [Google Scholar](https://scholar.google.com/citations?user=wnfrXdMAAAAJ&hl=en), [arXiv](https://arxiv.org/search/?query=%22shiyue+li%22&searchtype=all&source=header) and [Email](mailto:shiyueli@umich.edu)."  ]

[params.research]
    enable = true
    title = "Research"

[params.teaching]
    enable = true
    title = "Teaching"

[params.misc]
    enable = true
    title = "Music"

[params.expository]
    enable = false
    title = "Expository"

[params.travel]
    enable = false
    title = "Travel"


[params.footer]
    enable = true
