baseURL = "https://shiyue-li.github.io/"
languageCode = "en-us"
publishDir = "/Users/admin/Documents/GitHub/shiyue-li.github.io/"
title = "Shiyue Li"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-XXXXXXXX-Y"

[params]
    theme_color = "#574CDD"
    description = "Shiyue Li"
    description_photo = "portfolio.png" # need update
    favicon = "favicon.png"  # need update
    logo = "logo.png"  # need update
    email = "shiyue_li@brown.edu"
    github = "https://github.com/shiyue-li"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar.jpg"
    subtitle = "Shiyue Li."
    hero_right = ["**Curiouser and curiouser!**",
    "I'm a PhD student in Mathematics at [Brown University](https://www.brown.edu/academics/math/). My advisor is [Melody Chan](https://www.math.brown.edu/~mtchan/).",
    "My current research interest is to study enumerative and intersection problems in algebraic geometry and arithmetic geometry, using techniques from combinatorics and representation theory.",
    "I was a Lang Fellow at [Yale](https://math.yale.edu/) 2017-2019 and had wonderful four years of undergrad at [Harvey Mudd College](https://www.hmc.edu) studying math, CS and music.",
    "In Spring 2020, I'm co-organizing [AMS Annual Graduate Student Conferences](https://sites.google.com/a/brown.edu/ams-conference-2018/) at Brown with [Sam Freedman](https://www.math.brown.edu/~samjfree/). ",
    "In 2019-2020, I'm co-organizing the [Brown DRP](https://www.math.brown.edu/~drp/) with [Kyle Ferendo](https://www.math.brown.edu/~kferendo/) and Jiahua Zou.",
    "In Summer 2018 and 2019, I had loads of fun teaching at [Canada/USA Mathcamp](https://www.mathcamp.org).",
    ]

    resume = "shiyueli_cv.pdf"  # need update

[params.research]
    enable = true
    title = "Research"

[params.teaching]
    enable = true
    title = "Teaching"

[params.travel]
    enable = true
    title = "Travels"

[params.misc]
    enable = true
    title = "Miscellaneous"

[params.footer]
    enable = true
