baseURL = ""
languageCode = "en-us"
publishDir = "/Users/admin/Documents/GitHub/shiyue-li.github.io/"
title = "Shiyue Li"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-XXXXXXXX-Y"

[params]
    theme_color = "#574CDD"
    description = "Shiyue Li"
    description_photo = "portfolio.jpg" # need update
    favicon = "favicon.png"  # need update
    logo = "logo.png"  # need update
    email = "(first_name)[dot](last_name)[at]yale.edu"
    # facebook = "lex.collado"  # need update
    # twitter = "lexiscollado"  # need update
    # dribbble = "alexiscollado"  # need update
    # linkedin = "https://www.linkedin.com/in/alexander-hans-collado-jr-9444146a"
    medium = "ahvccollado"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar.jpg"
    subtitle = "I'm Shiyue."
    hero_right = ["**Hello!**"]
    resume = "ResumeCollado.pdf"  # need update

[params.research]
    enable = true
    title = "My Research"
    subtitle = "Research in Mathematics"

[params.case_studies]
    enable = true
    title = "Case Studies"
    subtitle = "Selected Works"

[params.footer]
    enable = true
