baseURL = "https://shiyue-li.github.io/"
languageCode = "en-us"
publishDir = "/Users/sli/Desktop/GitHub/shiyue-li.github.io/"
title = "Shiyue Li"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-XXXXXXXX-Y"
hasCJKLanguage = true

[params]
    theme_color = "#426BBA"
    description = "李诗乐"
    description_photo = "portfolio.png" # need update
    favicon = "favicon.png"  # need update
    logo = "logo.png"  # need update


[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar.jpg"
    subtitle = "Shiyue Li 詩樂"
    hero_right = [
    "I'm a PhD student in Mathematics at [Brown University](https://www.brown.edu/academics/math/). I'm fortunate to be advised by [Melody Chan](https://www.math.brown.edu/~mtchan/).",
    "My research interest is in combinatorial algebraic geometry. More specifically, I think about tropical geometry, moduli spaces of curves, Schubert calculus, geometric models and invariants of matroids.",
    "Prior to Brown, I was at [Yale University](https://math.yale.edu/) and [Harvey Mudd College](https://www.hmc.edu), doing math and (an excessive amount of) music. My undergrad thesis work was advised by [Dagan Karp](https://www.math.hmc.edu/~dk/).",
    "I also enjoy computing and AI, and worked at [Google Research](https://research.google/).",
    "Here are my [CV](http://www.shiyue.li/shiyueli_academic_CV_2022.pdf), [Google Scholar](https://scholar.google.com/citations?user=wnfrXdMAAAAJ&hl=en), [arXiv](https://arxiv.org/search/?query=%22shiyue+li%22&searchtype=all&source=header) and [Email](mailto:shiyue_li@brown.edu)."  ]

[params.research]
    enable = true
    title = "Research"

[params.teaching]
    enable = true
    title = "Teaching"

[params.expository]
    enable = false
    title = "Expository"

[params.travel]
    enable = false
    title = "Travel"

[params.misc]
    enable = true
    title = "Misc"

[params.footer]
    enable = true
