baseURL = ""
languageCode = "en-us"
publishDir = "/Users/admin/Documents/GitHub/shiyue-li.github.io/"
title = "Shiyue Li"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-XXXXXXXX-Y"

[params]
    theme_color = "#574CDD"
    description = "Shiyue Li"
    description_photo = "portfolio.jpg" # need update
    favicon = "favicon.png"  # need update
    logo = "logo.png"  # need update
    email = "(first_name)[dot](last_name)[at]yale.edu"
    # facebook = "lex.collado"  # need update
    # twitter = "lexiscollado"  # need update
    # dribbble = "alexiscollado"  # need update
    # linkedin = "https://www.linkedin.com/in/alexander-hans-collado-jr-9444146a"
    medium = "ahvccollado"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar.jpg"
    subtitle = "Shiyue Li."
    hero_right = ["**Curiouser and curiouser!**",
    "I'm a first year PhD student, and a Lang Fellow at the [Mathematics department of Yale University](https://math.yale.edu).",
    "I converged to my current stage of life via wonderful four years at [Harvey Mudd College](https://www.hmc.edu).",
    "Currently mentor at [Canada/USA Mathcamp 2018](https://www.mathcamp.org), I have a lot of fun teaching and working with awesome friends here at Mathcamp",
    ]
    # "I'm a first year PhD student, and a Lang Fellow at the Mathematics department of Yale University.
    # I converged to my current stage of life via Harvey Mudd College.
    # Born and raised in Jiangsu, China, I started my adventure in the U.S. as a member
    # of the Summer Science Program NM 2012."]
    resume = "shiyueli_cv.pdf"  # need update

[params.research]
    enable = true
    title = "My Research"
    subtitle = "Research in Mathematics"

[params.case_studies]
    enable = true
    title = "Math Notes"
    subtitle = "Notes for math classes that I teach."

[params.footer]
    enable = true
