baseURL = "https://shiyue-li.github.io/"
languageCode = "en-us"
publishDir = "/Users/admin/Documents/GitHub/shiyue-li.github.io/"
title = "Shiyue Li"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-XXXXXXXX-Y"

[params]
    theme_color = "#574CDD"
    description = "Shiyue Li"
    description_photo = "portfolio.png" # need update
    favicon = "favicon.png"  # need update
    logo = "logo.png"  # need update
    email = "shiyue_li@brown.edu"
    github = "https://github.com/shiyue-li"
    googlescholar = "https://scholar.google.com/citations?user=wnfrXdMAAAAJ&hl=en"


[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar.jpg"
    subtitle = "Shiyue Li"
    hero_right = ["**Curiouser and curiouser!**",
    "I'm a PhD student in Mathematics at [Brown University](https://www.brown.edu/academics/math/). I'm fortunate to be advised by [Melody Chan](https://www.math.brown.edu/~mtchan/).",
    "My current research interest is to study enumerative and intersection problems in algebraic geometry and arithmetic geometry, using techniques from combinatorics and representation theory.",
    "Prior to Brown, I was a Lang Fellow at [Yale](https://math.yale.edu/) 2017-2019 where I got my master's degree in math.",
    "I spent wonderful four years of undergrad at [Harvey Mudd College](https://www.hmc.edu) studying math, CS and music.",
    "During undergrad, I enjoyed computing and AI. With that, I was lucky to work with amazing research scientists on an experimental project at [Google Research](https://research.google/).",
    "You can click on the four icons below my profile pic for my cv, email, github and google scholar, up to a permutation."
    ]

    resume = "shiyueli-2020jan.pdf"  # need update

[params.research]
    enable = true
    title = "Research"

[params.teaching]
    enable = true
    title = "Teaching"

[params.travel]
    enable = true
    title = "Travel"

[params.misc]
    enable = true
    title = "Misc"

[params.footer]
    enable = true
