baseURL = "https://shiyue-li.github.io/"
languageCode = "en-us"
publishDir = "/Users/admin/Documents/GitHub/shiyue-li.github.io/"
title = "Shiyue Li"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-XXXXXXXX-Y"
hasCJKLanguage = true

[params]
    theme_color = "#574CDD"
    description = "李诗乐"
    description_photo = "portfolio.png" # need update
    favicon = "favicon.png"  # need update
    logo = "logo.png"  # need update
    # email = "shiyue_li@brown.edu"
    # github = "https://github.com/shiyue-li"
    # googlescholar = "https://scholar.google.com/citations?user=wnfrXdMAAAAJ&hl=en"


[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar.jpg"
    subtitle = "Shiyue (詩樂) Li"
    hero_right = [
    "I'm a PhD student in Mathematics at [Brown University](https://www.brown.edu/academics/math/). I'm fortunate to be advised by [Melody Chan](https://www.math.brown.edu/~mtchan/).",
    "My research interests sit in the intersection of algebraic geometry, combinatorics and topology. More specifically, I think about matroids, Schubert calculus, enumerative geometry, moduli spaces of curves and their combinatorics induced by tropical geometry.",
    "Prior to Brown, I studied math at [Yale University](https://math.yale.edu/) and had spent wonderful four years of undergrad at [Harvey Mudd College](https://www.hmc.edu) doing math and music. My undergrad thesis work was advised by [Dagan Karp](https://www.math.hmc.edu/~dk/).",
    "I also enjoyed computing and AI, while working at [Google Research](https://research.google/).",
    "Here are my [CV](http://www.shiyue.li/shiyueli_cv_2020.pdf), [GitHub](https://github.com/shiyue-li), [Google Scholar](https://scholar.google.com/citations?user=wnfrXdMAAAAJ&hl=en), and [Email](mailto:shiyue_li@brown.edu)."  ]

[params.research]
    enable = true
    title = "Research"

[params.teaching]
    enable = true
    title = "Teaching"

[params.expository]
    enable = false
    title = "Expository"

[params.travel]
    enable = false
    title = "Travel"

[params.misc]
    enable = true
    title = "Misc"

[params.footer]
    enable = true
