baseURL = "https://shiyue-li.github.io/"
languageCode = "en-us"
publishDir = "/Users/admin/Documents/GitHub/shiyue-li.github.io/"
title = "Shiyue Li"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-XXXXXXXX-Y"

[params]
    theme_color = "#574CDD"
    description = "Shiyue Li"
    description_photo = "portfolio.png" # need update
    favicon = "favicon.png"  # need update
    logo = "logo.png"  # need update
    # email = "shiyue_li@brown.edu"
    # github = "https://github.com/shiyue-li"
    # googlescholar = "https://scholar.google.com/citations?user=wnfrXdMAAAAJ&hl=en"


[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar.jpg"
    subtitle = "Shiyue Li"
    hero_right = ["**Curiouser and curiouser!**",
    "I'm a PhD student in Mathematics at [Brown University](https://www.brown.edu/academics/math/). I'm fortunate to be advised by [Melody Chan](https://www.math.brown.edu/~mtchan/).",
    "My research interests are enumerative geometry and combinatorics.",
    "Prior to Brown, I studied math at [Yale](https://math.yale.edu/) and had spent wonderful four years of undergrad at [Harvey Mudd College](https://www.hmc.edu) doing math and music.",
    "I also enjoyed computing and AI, while working at [Google Research](https://research.google/).",
    "Here are my [cv](http://www.shiyue.li/shiyueli_cv_2020.pdf), [github](https://github.com/shiyue-li), [google scholar](https://scholar.google.com/citations?user=wnfrXdMAAAAJ&hl=en), and [email](mailto:shiyue_li@brown.edu)."  ]

[params.research]
    enable = true
    title = "Research"

[params.teaching]
    enable = true
    title = "Teaching"

[params.expository]
    enable = false
    title = "Expository"

[params.travel]
    enable = false
    title = "Travel"

[params.misc]
    enable = true
    title = "Misc"

[params.footer]
    enable = true
