baseURL = "https://shiyue-li.github.io/"
languageCode = "en-us"
publishDir = "/Users/sli/Desktop/GitHub/shiyue-li.github.io/"
title = "Shiyue Li"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-XXXXXXXX-Y"
hasCJKLanguage = true

[params]
    theme_color = "#426BBA"
    description = "李诗乐"
    description_photo = "portfolio.png" # need update
    favicon = "favicon.png"  # need update
    logo = "logo.png"  # need update


[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar.jpg"
    subtitle = "Shiyue Li 李詩樂"
    hero_right = [
    "I am a mathematician at the [Institute for Advanced Study](https://www.ias.edu), mentored by [June Huh](https://web.math.princeton.edu/~huh/).",
    "My research interest is combinatorial algebraic geometry. More specifically, I think about: ",
    "* K-theory, Hodge structures and intersection theory of moduli spaces of curves,",
    "* geometric models and invariants of matroidal structures,",
    "* applications of algebraic geometry to combinatorics.",
    "Prior, I did my PhD at [Brown University](https://www.brown.edu/academics/math/) and my undergraduate studies in math and music at [Harvey Mudd College](https://www.hmc.edu), where I was fortunate to be advised by [Melody Chan](https://www.math.brown.edu/~mtchan/) and [Dagan Karp](https://www.math.hmc.edu/~dk/) respectively.",
    "Here are my [Curriculum Vitae](http://www.shiyue.li/shiyueli-website-2023.pdf), [Google Scholar](https://scholar.google.com/citations?user=wnfrXdMAAAAJ&hl=en), [arXiv](https://arxiv.org/search/?query=%22shiyue+li%22&searchtype=all&source=header) and [Email](mailto:shiyue_li@ias.edu)."  ]

[params.research]
    enable = true
    title = "Research"

[params.teaching]
    enable = true
    title = "Teaching"

[params.expository]
    enable = false
    title = "Expository"

[params.travel]
    enable = false
    title = "Travel"

[params.misc]
    enable = false
    title = "Misc"

[params.footer]
    enable = true
